.TH SCOUNT 1 "September 2026" "Alphanet/STCL" "User Commands"
.SH NAME
scount \- A tool to count logical lines of code and other metrics
.SH SYNOPSIS
.B scount
[options]
.I <PATH>
.SH DESCRIPTION
scount counts source code lines in a single file
or all files in a directory as specified by
.IR PATH .
.PP
When the
.B \-\-annotate\-counts
option is used, scount marks counted logical lines and writes the
annotated source to standard output. This option can only be used when
.I PATH
refers to a single input file.
.PP
The output uses the following abbreviations for the computed metrics:
.TS
box left tab(|);
Cb Cb
L L.
Abbr.|Description
LLC|Logical lines of code
LOC|Physical lines of code
PHL|Hard physical lines
WRD|Number of words
CHR|Number of characters
SZE|File size in bytes
.TE
.SH ARGUMENTS
.TP
.I <PATH>
The path to the input file or directory to process.
.br
This is a mandatory argument.
.br
Use
.B \-
to read source text from standard input instead and treat it as plain text.
Use
.B \-.EXT
to read source text from standard input and treat it as if it was a file with the
specified file extension. For example,
.B \-.java
to treat the data provided via stdin as Java source code.
.SH OPTIONS
.TP
.B \-\-annotate\-counts
Mark counted logical lines and output the result.
.br
This option can only be used on a single file input.
.TP
.B \-l, \-\-lines
Compute and display only line-specific metrics.
.br
This includes logical lines of code (LLC), physical lines of code (LOC)
and hard physical lines (PHL).
.TP
.B \-\-show\-files
Show a table of individual files in the result when the given input path refers to a directory.
.br
For a large number of files, a condensed view is shown.
.TP
.B \-\-show\-all\-files
Show a table of all individual files in the result when the given input path refers to a directory.
.br
All files are listed regardless of how many there are.
.TP
.B \-\-stop\-on\-error
Stop the processing on the first encountered error,
even for non\-critical errors. Without this option (the default),
some errors are considered non-critical, in which case the corresponding
file is skipped and the processing continues.
.TP
.B \-\-strict
Use strict syntax checking for source code files when counting logical lines.
If set, any syntax error detected in the source code will cause the
processing of logical lines of code to fail for the affected file and the overall
operation will continue. Without this option (the default), partial syntax errors
are tolerated. If an entire source file is syntactically invalid, the processing
for that file still fails regardless of this option.
.TP
.B \-\-verbose
Enable verbose output.
.TP
.B \-#, \-\-version
Show program version information.
.TP
.B \-?, \-\-help
Show a help message.
.SH EXIT STATUS
.TP
.B 0
The operation has completed successfully.
.TP
.B 1
An invalid argument was provided.
.TP
.B 2
A file given as an input was invalid.
.TP
.B 3
Nothing was processed for the given input.
.TP
.B 4
An I/O error has occurred for the input or output stream.
.TP
.B 126
An unspecified error has occurred.
.SH EXAMPLES
.TP
Count lines in a directory tree:
.RS
.nf
scount /path/to/project
.fi
.RE
.TP
Count source text of two files from standard input as plain text:
.RS
.nf
cat input1.txt input2.txt | scount -
.fi
.RE
.TP
Count lines of code from standard input using an explicit language extension:
.RS
.nf
scount -.java < Sample.java
.fi
.RE
.TP
Annotate logical lines and write to separate source file:
.RS
.nf
scount \-\-annotate\-counts mysrc.c > mymysrc_annotated.c
.fi
.RE
.SH REPORTING BUGS
Report any bugs to <https://github.com/raven-computing/reckon/issues>
.SH AUTHOR
Written by Phil Gaiser
.SH COPYRIGHT
Copyright (C) 2026 Raven Computing
.br
This software is licensed under the Apache License, Version 2.0
.SH SEE ALSO
Full documentation <https://docs.raven-computing.com/reckon/latest>
